"""App configuration package."""

from config.constants import (
    APP_ICON,
    APP_TITLE,
    AUTO_REFRESH_INTERVAL,
    DEBUG,
    DEFAULT_GEMINI_MODEL,
    EXECUTIONS_CACHE_SEC,
    EXECUTIONS_LIMIT,
    GEMINI_MODEL,
    GEMINI_MODEL_KEYS,
    GEMINI_MODELS,
    GROQ_MODEL,
    LLM_PROVIDERS,
    N8N_REQUEST_TIMEOUT,
    OPENAI_MODEL,
)

__all__ = [
    "APP_ICON",
    "APP_TITLE",
    "AUTO_REFRESH_INTERVAL",
    "DEBUG",
    "DEFAULT_GEMINI_MODEL",
    "EXECUTIONS_CACHE_SEC",
    "EXECUTIONS_LIMIT",
    "GEMINI_MODEL",
    "GEMINI_MODEL_KEYS",
    "GEMINI_MODELS",
    "GROQ_MODEL",
    "LLM_PROVIDERS",
    "N8N_REQUEST_TIMEOUT",
    "OPENAI_MODEL",
]
